@startuml

class Sim {
  + update(dt)
}

class Actor {
  + update(dt)
}

class Component {
  + update(dt)
}

Sim "1" *-- "*" Actor: actors
Actor "1" *-- "1" Region: nimbus
Actor "1" *-left- "*" Component: composants

class Region <<abstract>> {
  - acteurParent
  + test(Actor)
}
class Cube {}
class Sphere {}
class Cylindre {}

Region <|-- Cube
Region <|-- Sphere
Region <|-- Cylindre
@enduml