@startuml

[*] --> Wander
Wander -right-> Flee: Awa Humain > 0.6
Flee -left-> Wander: Awa Humain < 0.2


Wander -down-> SearchFood: barre\nd'energie\nfaible

Wander: Choisi une destination\naléatoire et s'y rend.
Flee: Le pingouin fuit l'humain.
SearchFood: Lorsqu'il se déplace\nle pengouin perd de\nl'énergie.\nIl cherche alors de l'herbe\npour la manger.
Eat: Le pingouin mange l'herbe.

@enduml
